include ../common/begin.mk

NAME := HelloWorld

NATIVE_OPTS := \
  -H:IncludeResources=.* \
  -H:Log=registerResource: \
  --emit=build-report

include $(COMMON)/end.mk


#   -H:IncludeResources=lib/libhelloworld.1.2.3.so \
#   -H:ResourceConfigurationFiles=resources.json \
